name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Install ldid for macOS code signing
      run: |
        wget https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_linux_x86_64
        chmod +x ldid_linux_x86_64
        sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

    - name: Build binaries
      run: npm run build:all

    - name: List generated binaries
      run: ls -la binaries/
    
    - name: Code sign macOS binaries
      run: |
        ldid -S binaries/codegen-cloner-macos-x64
        ldid -S binaries/codegen-cloner-macos-arm64

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          binaries/index-linux-x64
          binaries/index-macos-x64
          binaries/index-macos-arm64
          binaries/index-win-x64.exe
          install.sh
          install.ps1
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Rename binaries for release
      run: |
        mv binaries/index-linux-x64 binaries/codegen-cloner-linux-x64
        mv binaries/index-macos-x64 binaries/codegen-cloner-macos-x64
        mv binaries/index-macos-arm64 binaries/codegen-cloner-macos-arm64
        mv binaries/index-win-x64.exe binaries/codegen-cloner-win-x64.exe

    - name: Update release with renamed binaries
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          binaries/codegen-cloner-linux-x64
          binaries/codegen-cloner-macos-x64
          binaries/codegen-cloner-macos-arm64
          binaries/codegen-cloner-win-x64.exe
          install.sh
          install.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}